### ISSUE TITLE
Graceful handling of malformed RequestData

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#120]
Invalid JSON or invalid form content should result in a 400 response.

Also consider if we want to tweak the behavior around empty content at all (at the moment we return `None`)

**Comment by piotr-szpetkowski** [comment]
👍 Right now if I try to e.g. send a POST request with no data I get 500:

```
apistar/http.py", line 187, in build
    value = data[arg_name]  # type: ignore
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pavelholvi** [comment]
Hey, has there been any updates on this? How do I reproduce this? Doing something like
```
>>> requests.post('http://127.0.0.1:8080/')
<Response [200]>
```
works OK.

**Comment by tomchristie** [comment]
Eg. Make a POST request with a content-type header set to application/json, and a body containing some invalid bytes that cannot be parsed as JSON.

**Comment by pavelholvi** [comment]
```
>>> requests.post('http://127.0.0.1:8080/',  json=b'123')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/isaevpd/py_virtual_envs/apistar_test/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/isaevpd/py_virtual_envs/apistar_test/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/isaevpd/py_virtual_envs/apistar_test/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/Users/isaevpd/py_virtual_envs/apistar_test/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/isaevpd/py_virtual_envs/apistar_test/lib/python3.6/site-packages/requests/models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "/Users/isaevpd/py_virtual_envs/apistar_test/lib/python3.6/site-packages/requests/models.py", line 458, in prepare_body
    body = complexjson.dumps(json)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```
Is this the way to reproduce?

**Comment by tomchristie** [comment]
No not quite - that's `requests` raising an error because you're trying to create a malformed request. You'd need to do something like `headers={'Content-Type': 'application/json'}, data='123abc'` in order to coerce it into creating an invalid JSON request.

**Comment by pavelholvi** [comment]
Oh, sorry. Created a testcase here:
```
    @pytest.mark.parametrize('client', [wsgi_client, async_client])
    def test_invalid_json(client):
        response = client.post(
            'http://example.com/data/',
            headers={'content-type': 'application/json'},
>           data='"hello": 123}'
        )

tests/test_http.py:359:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../py_virtual_envs/apistar_dev/lib/python3.6/site-packages/requests/sessions.py:555: in post
    return self.request('POST', url, data=data, json=json, **kwargs)
apistar/test.py:249: in request
    return super().request(method, url, **kwargs)
../../py_virtual_envs/apistar_dev/lib/python3.6/site-packages/requests/sessions.py:508: in request
    resp = self.send(prep, **send_kwargs)
../../py_virtual_envs/apistar_dev/lib/python3.6/site-packages/requests/sessions.py:618: in send
    r = adapter.send(request, **kwargs)
apistar/test.py:113: in send
    wsgi_response = self.app(environ, start_response)
apistar/frameworks/wsgi.py:115: in __call__
    response = self.http_injector.run(self.exception_handler, state=state)
apistar/components/dependency.py:110: in run
    ret = step.func(**kwargs)
apistar/frameworks/wsgi.py:112: in __call__
    response = self.http_injector.run(handler, state=state)
apistar/components/dependency.py:110: in run
    ret = step.func(**kwargs)
apistar/components/wsgi.py:85: in get_request_data
    value = json.loads(body.decode('utf-8'))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py:354: in loads
    return _default_decoder.decode(s)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <json.decoder.JSONDecoder object at 0x103d336d8>, s = '"hello": 123}'
_w = <built-in method match of _sre.SRE_Pattern object at 0x103967f30>

    def decode(self, s, _w=WHITESPACE.match):
        """Return the Python representation of ``s`` (a ``str`` instance
            containing a JSON document).

            """
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        end = _w(s, end).end()
        if end != len(s):
>           raise JSONDecodeError("Extra data", s, end)
E           json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py:342: JSONDecodeError
```

**Comment by tomchristie** [comment]
Yup!

**Comment by audiolion** [comment]
sorry for the off topic, but @pavelholvi how did you do the Line 85 inline from that file at that commit? looks groovy! 🎉

**Comment by pavelholvi** [comment]
copy-paste
```
https://github.com/encode/apistar/blob/c64181be24db00809b315b96d4ba1f422285f4f8/apistar/components/wsgi.py#L85
```

**Comment by pavelholvi** [comment]
Caveman-style fix here, please have a look when you have a moment:
https://github.com/encode/apistar/pull/277

**Comment by audiolion** [comment]
this got merged so we can close now!
