### ISSUE TITLE
ImportError: cannot import name 'DefaultProvider'

### ISSUE THREAD

**Issue by EssaAlshammri** [tomchristie/apistar#206]
Hi,
I don't know if this belongs here or at pipenv! but there you go.

all I did was
`pipenv --three`
`pipenv shell`
`pipenv install apistar`
`pipenv lock`

and when I try `apistar new . --layout minimal`

I get this:

```
Traceback (most recent call last):
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/bin/apistar", line 7, in <module>
    from apistar.main import main
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/apistar/__init__.py", line 8, in <module>
    from apistar.app import App
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/apistar/app.py", line 7, in <module>
    from apistar import commands as cmd
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/apistar/commands/__init__.py", line 4, in <module>
    from apistar.commands.schema import schema
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/apistar/commands/schema.py", line 2, in <module>
    from coreapi.utils import get_installed_codecs
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/coreapi/__init__.py", line 2, in <module>
    from coreapi import auth, codecs, exceptions, transports, utils
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/coreapi/codecs/__init__.py", line 3, in <module>
    from coreapi.codecs.corejson import CoreJSONCodec
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/coreapi/codecs/corejson.py", line 8, in <module>
    import coreschema
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/coreschema/__init__.py", line 6, in <module>
    from coreschema.encodings.html import render_to_form
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/coreschema/encodings/html.py", line 5, in <module>
    env = jinja2.Environment(loader=jinja2.PackageLoader('coreschema', 'templates'))
  File "/home/essa/.local/share/virtualenvs/apistart-test-snB09WnE/lib/python3.5/site-packages/jinja2/loaders.py", line 222, in __init__
    from pkg_resources import DefaultProvider, ResourceManager, \
ImportError: cannot import name 'DefaultProvider'
```
thanks

**Comment by tomchristie** [comment]
From the traceback the import error seems to occur within jinja2.
I'd start be trying to track down if you can reproduce that error further down the stack (eg. importing `coreschema`, importing `jinja2`.)
