### ISSUE TITLE
Using gunicorn if using http.QueryParams without query params causes KeyError

### ISSUE THREAD

**Issue by kinabalu** [tomchristie/apistar#51]
```
[2017-04-16 20:24:24 -0700] [67301] [ERROR] Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/apistar/app.py", line 68, in func
    state[output] = function(**kwargs)
  File "app.py", line 27, in build
    return cls(url_decode(environ['QUERY_STRING']))
KeyError: 'QUERY_STRING'
```

**Comment by tomchristie** [comment]
Closed via #56, #52
